// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/goflow-atom/goflow-service/internal/app"
	"github.com/goflow-atom/goflow-service/internal/server"
)

// Injectors from wire.go:

// InitializeApplication initializes the entire application with all dependencies.
//
// This function is a Wire injector that uses the app.ProviderSet to create
// all required dependencies and return a fully configured server instance.
//
// Wire will generate the actual implementation in wire_gen.go.
//
// Returns:
//   - *server.Server: Fully configured HTTP server with all dependencies
//   - func(): Cleanup function to be called on shutdown
//   - error: Error if initialization fails
//
// Example:
//
//	srv, cleanup, err := InitializeApplication()
//	if err != nil {
//	    log.Fatal(err)
//	}
//	defer cleanup()
func InitializeApplication() (*server.Server, func(), error) {
	config, err := app.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	serverConfig := app.ProvideServerConfig(config)
	logger, err := app.ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	serverServer, err := app.ProvideServer(serverConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	return serverServer, func() {
	}, nil
}
